### ISSUE TITLE
Possible bug in ChessEngine.getLegalMoves

### ISSUE THREAD

**Issue by simondh** [jvarsoke/ictk#11]
We are doing a college project to develop a chess game, and your library looked ideal. However I started writing Junit tests for the first step, getting legal moves, and I think I may have found a bug. Starting with a new board, For Black pawns, ITCK returns an array or 3 or 4 legal moves. For white pawns it is fine, two legal moves in same file, rank 3 and 4,  for Knights it is fine and for the rest it returns size==0, as expected. 

Source is https://github.com/simondh/ChessEngine
Test is in tests/chessEngineTest.java, fails at line 44
Source is src/ChessEngine.java, getLegalMoves, starting at line 97. 
and test output is below:

Any help MUCH APPRECIATED, and if its me, guidance also appreciated. 

simon.d.hewitt@gmail.com

size : 2 rank : 8 File :2 Piece : Knight
size : 2 rank : 8 File :7 Piece : Knight
size : 3 rank : 7 File :1 Piece : Pawn

java.lang.AssertionError: Black Pawn has two legal moves 
Expected :2
Actual   :3
   <Click to see difference>

	
size : 2 rank : 2 File :1 Piece : Pawn
size : 2 rank : 2 File :2 Piece : Pawn
size : 2 rank : 2 File :3 Piece : Pawn
size : 2 rank : 2 File :4 Piece : Pawn
size : 2 rank : 2 File :5 Piece : Pawn
size : 2 rank : 2 File :6 Piece : Pawn

**Comment by jvarsoke** [comment]
Hi Simon.  I looked through your code to figure out why your assertions are failing.  I believe the issue is that you are looking at the "Black" legal moves but it is "White's" turn to move on the board.  So, really the Black Pawns have no "legal" moves (because it's not their turn to move).  The library could be overly aggressive in enforcing this nonsensical query, but the LegalMoves of the non-moving side are internally used to determine the moving-side's King's possible moves.

The reason you are getting 3 is because the capture move of the Black pawn on the A-file is generated a7xb6.  You'll notice the Black pawn on b7 returns 4 "legal" moves.

I would not consider this a bug -- just a nonsensical usage.  If you call setBlackMove(true) on the ChessBoard, you'll get the expected 2 LegalMoves returned from each Pawn.

Good luck in your project.  Feel free to ask more questions.
